import numpy as np
import pandas as pd
import os

def create_readable_summary():
    output_file = "Outputs/Pretrained_HIV/embeddings_summary_readable.txt"
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w') as f:
        f.write("=== HUMAN READABLE EMBEDDINGS SUMMARY ===\n")
        f.write("This file demonstrates exactly what is inside the .npy files generated by ESM-2.\n\n")
        
        # Load one antibody
        ab_dir = "Outputs/Pretrained_HIV/ab"
        if os.path.exists(ab_dir):
            ab_files = os.listdir(ab_dir)
            if ab_files:
                ab_name = ab_files[0]
                ab_emb = np.load(os.path.join(ab_dir, ab_name))
                f.write(f"--- ANTIBODY: {ab_name} ---\n")
                f.write(f"Shape: {ab_emb.shape}  -> (Max_Sequence_Length, 320_ESM_Features)\n")
                f.write("Explanation: Every row represents a single amino acid position.\n")
                f.write("Each position is described by 320 numbers that encode its biology, structure, and evolution.\n\n")
                
                f.write("Snippet of the first amino acid position (First 10 features out of 320):\n")
                f.write(f"{ab_emb[0, :10]}\n\n")
                
                f.write("Snippet of the 50th amino acid position (First 10 features out of 320):\n")
                f.write(f"{ab_emb[49, :10]}\n\n")
        
        # Load one antigen
        ag_dir = "Outputs/Pretrained_HIV/ag"
        if os.path.exists(ag_dir):
            ag_files = os.listdir(ag_dir)
            if ag_files:
                ag_name = ag_files[0]
                ag_emb = np.load(os.path.join(ag_dir, ag_name))
                f.write(f"--- VIRUS ANTIGEN: {ag_name} ---\n")
                f.write(f"Shape: {ag_emb.shape}  -> (Max_Sequence_Length, 320_ESM_Features)\n")
                f.write("Explanation: Same as above, but padded to the max virus length.\n\n")
                
                f.write("Snippet of the first amino acid position (First 10 features out of 320):\n")
                f.write(f"{ag_emb[0, :10]}\n\n")
                
    print(f"Readable summary generated at: {output_file}")

if __name__ == "__main__":
    create_readable_summary()
